🔥팔로우 추천 알고리즘 수정
DEMODAY-devStory/backend pull request #34
Opened 2022-10-31 16:55 UTC by taeho0888

확인 부탁드려요~

2022-10-31 16:58 UTC, taeho0888 commented on mainfeed/urls.py
> +    path('recommend/<str:pk>/', RecommendView.as_view()),
modelviewset에서 ListAPIView로 수정

2022-10-31 16:58 UTC, taeho0888 commented on mainfeed/views.py
> +
편의를 위해 request.user의 profile과 해시태그 명단을 my_profile, my_hashtag의 쿼리셋 타입으로 저장

2022-10-31 16:59 UTC, taeho0888 commented on mainfeed/views.py
> +
- request.user를 제외한 해당 해시태그를 가진 모든 profile을 user_queryset에 저장
- request.user가 팔로우하는 유저 리스트를 following_queryset에 저장
- user_queryset과 following_queryset의 차집합을 쿼리셋 타입이 아닌 리스트 타입으로 user_list에 저장

2022-10-31 17:00 UTC, taeho0888 commented on mainfeed/views.py
> +
- commonhashdict라는 딕셔너리를 만들어 user_list의 유저들이 request.user와 몇개의 해시태그가 겹치는 지 저장
 {"userid" : 겹치는 hashtag 갯수 } 형식
- commonhashdict를 value의 내림차순으로 정렬

2022-10-31 17:01 UTC, taeho0888 commented on mainfeed/views.py
> +
빈 queryset을 만들고, 이에 commonhashdict의 유저를 profile 클래스를 차례로 넣음

2022-11-01 15:27 UTC, dahyen0o requested changes
질문... 왜 주소에 해시태그를 붙이는 거죠?? 이전 알고리즘과 달리 특정 해시태그에 대해 유저를 추천하는 게 아닌데

2022-11-02 05:21 UTC, merged